// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/african-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/african-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/african-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/armenian-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/armenian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/armenian-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../src/app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chinese-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chinese-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/chinese-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/faq/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/faq">> = Specific
  const handler = {} as typeof import("../../src/app/faq/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/filipino-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/filipino-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/filipino-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/films/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/films/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/films/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/four-seasons-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/four-seasons-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/four-seasons-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/indian-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/indian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/indian-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jewish-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/jewish-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/jewish-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/malibu-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/malibu-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/malibu-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pelican-hill-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pelican-hill-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/pelican-hill-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/persian-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/persian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/persian-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/photography/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/photography">> = Specific
  const handler = {} as typeof import("../../src/app/photography/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/pricing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pricing">> = Specific
  const handler = {} as typeof import("../../src/app/pricing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/referral-venues/[venue]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral-venues/[venue]">> = Specific
  const handler = {} as typeof import("../../src/app/referral-venues/[venue]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/referral/[planner]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/referral/[planner]">> = Specific
  const handler = {} as typeof import("../../src/app/referral/[planner]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/reviews/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/reviews">> = Specific
  const handler = {} as typeof import("../../src/app/reviews/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/south-asian-wedding-videographer/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/south-asian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/south-asian-wedding-videographer/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/video-test/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/video-test">> = Specific
  const handler = {} as typeof import("../../src/app/video-test/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/videography/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/videography">> = Specific
  const handler = {} as typeof import("../../src/app/videography/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/contact/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contact">> = Specific
  const handler = {} as typeof import("../../src/app/api/contact/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/african-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/african-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/african-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/armenian-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/armenian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/armenian-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/chinese-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/chinese-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/chinese-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/filipino-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/filipino-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/filipino-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/jewish-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/jewish-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/jewish-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/persian-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/persian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/persian-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/south-asian-wedding-videographer/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/south-asian-wedding-videographer">> = Specific
  const handler = {} as typeof import("../../src/app/south-asian-wedding-videographer/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
