// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/african-wedding-videographer" | "/armenian-wedding-videographer" | "/blog" | "/blog/[slug]" | "/chinese-wedding-videographer" | "/faq" | "/filipino-wedding-videographer" | "/films/[slug]" | "/four-seasons-wedding-videographer" | "/indian-wedding-videographer" | "/jewish-wedding-videographer" | "/malibu-wedding-videographer" | "/pelican-hill-wedding-videographer" | "/persian-wedding-videographer" | "/photography" | "/pricing" | "/referral-venues/[venue]" | "/referral/[planner]" | "/reviews" | "/south-asian-wedding-videographer" | "/video-test" | "/videography"
type AppRouteHandlerRoutes = "/api/contact"
type PageRoutes = never
type LayoutRoutes = "/" | "/african-wedding-videographer" | "/armenian-wedding-videographer" | "/chinese-wedding-videographer" | "/filipino-wedding-videographer" | "/jewish-wedding-videographer" | "/persian-wedding-videographer" | "/south-asian-wedding-videographer"
type RedirectRoutes = "/nigerian-wedding-videographer"
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/african-wedding-videographer": {}
  "/api/contact": {}
  "/armenian-wedding-videographer": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/chinese-wedding-videographer": {}
  "/faq": {}
  "/filipino-wedding-videographer": {}
  "/films/[slug]": { "slug": string; }
  "/four-seasons-wedding-videographer": {}
  "/indian-wedding-videographer": {}
  "/jewish-wedding-videographer": {}
  "/malibu-wedding-videographer": {}
  "/nigerian-wedding-videographer": {}
  "/pelican-hill-wedding-videographer": {}
  "/persian-wedding-videographer": {}
  "/photography": {}
  "/pricing": {}
  "/referral-venues/[venue]": { "venue": string; }
  "/referral/[planner]": { "planner": string; }
  "/reviews": {}
  "/south-asian-wedding-videographer": {}
  "/video-test": {}
  "/videography": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/african-wedding-videographer": never
  "/armenian-wedding-videographer": never
  "/chinese-wedding-videographer": never
  "/filipino-wedding-videographer": never
  "/jewish-wedding-videographer": never
  "/persian-wedding-videographer": never
  "/south-asian-wedding-videographer": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
